-- Απογραφή (Stock Count / Inventory) tables.

CREATE TABLE IF NOT EXISTS stock_count_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  store_id UUID NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'finalized')),
  counted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_count_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES stock_count_sessions(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  product_variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,
  system_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
  counted_quantity NUMERIC(12,3) NULL,
  UNIQUE(session_id, product_variant_id)
);

CREATE INDEX IF NOT EXISTS stock_count_sessions_company_idx ON stock_count_sessions(company_id);
CREATE INDEX IF NOT EXISTS stock_count_sessions_store_idx ON stock_count_sessions(store_id);
CREATE INDEX IF NOT EXISTS stock_count_lines_session_idx ON stock_count_lines(session_id);
