-- Ενδοδιακίνηση (Inter-warehouse Transfer) tables.

CREATE TABLE IF NOT EXISTS transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  source_store_id UUID NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  dest_store_id UUID NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'posted', 'reversed')),
  created_by UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT transfers_stores_different CHECK (source_store_id <> dest_store_id)
);

CREATE TABLE IF NOT EXISTS transfer_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id BIGINT NOT NULL REFERENCES transfers(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  product_variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,
  quantity NUMERIC(12,3) NOT NULL CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS transfers_company_idx ON transfers(company_id);
CREATE INDEX IF NOT EXISTS transfers_source_store_idx ON transfers(source_store_id);
CREATE INDEX IF NOT EXISTS transfers_dest_store_idx ON transfers(dest_store_id);
CREATE INDEX IF NOT EXISTS transfer_lines_transfer_idx ON transfer_lines(transfer_id);
