-- Migration: Receipts, Payments, and Payment Terms
-- Adds payment_terms to customers/vendors, payment fields to sales/purchases,
-- receipts and payments tables.

-- Payment terms on customers (values: immediate, 15, 30, 60, 90)
ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS payment_terms text NOT NULL DEFAULT 'immediate';
ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_payment_terms_check;
ALTER TABLE customers
  ADD CONSTRAINT customers_payment_terms_check
  CHECK (payment_terms IN ('immediate', '15', '30', '60', '90'));

-- Payment terms on vendors
ALTER TABLE vendors
  ADD COLUMN IF NOT EXISTS payment_terms text NOT NULL DEFAULT 'immediate';
ALTER TABLE vendors DROP CONSTRAINT IF EXISTS vendors_payment_terms_check;
ALTER TABLE vendors
  ADD CONSTRAINT vendors_payment_terms_check
  CHECK (payment_terms IN ('immediate', '15', '30', '60', '90'));

-- Payment fields on sales
ALTER TABLE sales
  ADD COLUMN IF NOT EXISTS payment_terms text NOT NULL DEFAULT 'immediate',
  ADD COLUMN IF NOT EXISTS due_date timestamp with time zone NULL,
  ADD COLUMN IF NOT EXISTS payment_status text NULL DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS amount_due numeric NULL;
ALTER TABLE sales
  DROP CONSTRAINT IF EXISTS sales_payment_terms_check;
ALTER TABLE sales
  ADD CONSTRAINT sales_payment_terms_check
  CHECK (payment_terms IN ('immediate', '15', '30', '60', '90'));
ALTER TABLE sales
  DROP CONSTRAINT IF EXISTS sales_payment_status_check;
ALTER TABLE sales
  ADD CONSTRAINT sales_payment_status_check
  CHECK (payment_status IS NULL OR payment_status IN ('unpaid', 'partial', 'paid', 'overdue'));

-- Payment fields on purchases
ALTER TABLE purchases
  ADD COLUMN IF NOT EXISTS payment_terms text NOT NULL DEFAULT 'immediate',
  ADD COLUMN IF NOT EXISTS due_date timestamp with time zone NULL,
  ADD COLUMN IF NOT EXISTS payment_status text NULL DEFAULT 'unpaid',
  ADD COLUMN IF NOT EXISTS amount_due numeric NULL;
ALTER TABLE purchases
  DROP CONSTRAINT IF EXISTS purchases_payment_terms_check;
ALTER TABLE purchases
  ADD CONSTRAINT purchases_payment_terms_check
  CHECK (payment_terms IN ('immediate', '15', '30', '60', '90'));
ALTER TABLE purchases
  DROP CONSTRAINT IF EXISTS purchases_payment_status_check;
ALTER TABLE purchases
  ADD CONSTRAINT purchases_payment_status_check
  CHECK (payment_status IS NULL OR payment_status IN ('unpaid', 'partial', 'paid', 'overdue'));

-- Receipts table (customer money in)
CREATE TABLE IF NOT EXISTS receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid NOT NULL REFERENCES companies(id),
  store_id uuid NOT NULL REFERENCES stores(id),
  sale_id bigint NULL REFERENCES sales(id),
  customer_id uuid NULL REFERENCES customers(id),
  amount numeric NOT NULL,
  payment_method_id uuid NOT NULL REFERENCES payment_methods(id),
  payment_date timestamp with time zone NOT NULL DEFAULT now(),
  notes text NULL,
  created_by uuid NULL REFERENCES users(id),
  is_auto boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS receipts_company_id_idx ON receipts(company_id);
CREATE INDEX IF NOT EXISTS receipts_store_id_idx ON receipts(store_id);
CREATE INDEX IF NOT EXISTS receipts_sale_id_idx ON receipts(sale_id);

-- Payments table (vendor money out)
CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_id uuid NOT NULL REFERENCES companies(id),
  store_id uuid NOT NULL REFERENCES stores(id),
  purchase_id bigint NULL REFERENCES purchases(id),
  vendor_id uuid NULL REFERENCES vendors(id),
  amount numeric NOT NULL,
  payment_method_id uuid NOT NULL REFERENCES payment_methods(id),
  payment_date timestamp with time zone NOT NULL DEFAULT now(),
  notes text NULL,
  created_by uuid NULL REFERENCES users(id),
  is_auto boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS payments_company_id_idx ON payments(company_id);
CREATE INDEX IF NOT EXISTS payments_store_id_idx ON payments(store_id);
CREATE INDEX IF NOT EXISTS payments_purchase_id_idx ON payments(purchase_id);
