-- =============================================================================
-- Invoice & Document Logic Refactor - Combined Migrations for Supabase
-- Run this in Supabase SQL Editor to apply all schema changes at once.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. product_variants: Add sale_price (default selling price per variant)
-- -----------------------------------------------------------------------------
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS sale_price NUMERIC(12,2) NULL;

COMMENT ON COLUMN product_variants.sale_price IS 'Default selling price for this variant. Per-store override in store_products.store_sale_price.';

-- -----------------------------------------------------------------------------
-- 2. store_products: Add reserved_quantity for Sales Order stock reservation
-- -----------------------------------------------------------------------------
ALTER TABLE store_products ADD COLUMN IF NOT EXISTS reserved_quantity NUMERIC(12,3) NOT NULL DEFAULT 0;

COMMENT ON COLUMN store_products.reserved_quantity IS 'Quantity reserved by open Sales Orders. Available = stock_quantity - reserved_quantity';

-- -----------------------------------------------------------------------------
-- 3. Purchases: Add PO document type, extend status values
-- -----------------------------------------------------------------------------
ALTER TABLE purchases DROP CONSTRAINT IF EXISTS purchases_document_type_check;
ALTER TABLE purchases ADD CONSTRAINT purchases_document_type_check CHECK (
  document_type IN ('PUR', 'SDN', 'DBN', 'PO')
);
COMMENT ON COLUMN purchases.document_type IS 'PO=Purchase Order, SDN=GRN Goods Received, PUR=Purchase Invoice, DBN=Purchase Credit Note';

ALTER TABLE purchases DROP CONSTRAINT IF EXISTS purchases_status_check;
ALTER TABLE purchases ADD CONSTRAINT purchases_status_check CHECK (
  status IN (
    'draft', 'ordered', 'received', 'completed', 'cancelled', 'invoiced',
    'sent', 'partially_received', 'closed', 'pending_invoice', 'reversed', 'credited', 'posted'
  )
);

-- -----------------------------------------------------------------------------
-- 4. Sales: Add SO document type, extend invoice_type
-- -----------------------------------------------------------------------------
ALTER TABLE sales DROP CONSTRAINT IF EXISTS sales_invoice_type_check;
ALTER TABLE sales ADD CONSTRAINT sales_invoice_type_check CHECK (
  invoice_type IN ('QUO', 'REC', 'INV', 'CRN', 'DNO', 'SO')
);
COMMENT ON COLUMN sales.invoice_type IS 'QUO=Quote, SO=Sales Order, DNO=Delivery Note, INV=Invoice, REC=Receipt, CRN=Credit Note';

-- -----------------------------------------------------------------------------
-- 5. Ενδοδιακίνηση (Inter-warehouse Transfer) tables
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  source_store_id UUID NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  dest_store_id UUID NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'posted', 'reversed')),
  created_by UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT transfers_stores_different CHECK (source_store_id <> dest_store_id)
);

CREATE TABLE IF NOT EXISTS transfer_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id BIGINT NOT NULL REFERENCES transfers(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  product_variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,
  quantity NUMERIC(12,3) NOT NULL CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS transfers_company_idx ON transfers(company_id);
CREATE INDEX IF NOT EXISTS transfers_source_store_idx ON transfers(source_store_id);
CREATE INDEX IF NOT EXISTS transfers_dest_store_idx ON transfers(dest_store_id);
CREATE INDEX IF NOT EXISTS transfer_lines_transfer_idx ON transfer_lines(transfer_id);

-- -----------------------------------------------------------------------------
-- 6. Απογραφή (Stock Count / Inventory) tables
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock_count_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  store_id UUID NOT NULL REFERENCES stores(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'finalized')),
  counted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS stock_count_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES stock_count_sessions(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  product_variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,
  system_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
  counted_quantity NUMERIC(12,3) NULL,
  UNIQUE(session_id, product_variant_id)
);

CREATE INDEX IF NOT EXISTS stock_count_sessions_company_idx ON stock_count_sessions(company_id);
CREATE INDEX IF NOT EXISTS stock_count_sessions_store_idx ON stock_count_sessions(store_id);
CREATE INDEX IF NOT EXISTS stock_count_lines_session_idx ON stock_count_lines(session_id);
